host = ${SCRAPPER_HOST}
port = ${SCRAPPER_PORT}
database{
    url = ${PG_URL}
    username = ${PG_USERNAME}
    password = ${PG_PASSWORD}
}
kafka{
    servers = ${KAFKA_BOOTSTRAP_SERVERS}
    topic = ${KAFKA_LINK_UPDATE_TOPIC}
}