host = ${SCRAPPER_HOST}
port = ${SCRAPPER_PORT}
database{
    url = ${PG_URL}
    username = ${PG_USERNAME}
    password = ${PG_PASSWORD}
}
kafka{
    servers = ${KAFKA_BOOTSTRAP_SERVERS}
    topic = ${KAFKA_LINK_UPDATE_TOPIC}
}
scrapper{
    link-process-milliseconds = 500
    check-interval-seconds = 10
    batch-size = 1
}
outbox{
    poll-interval-seconds = 10
    batch-size = 1
}
resilience{
    timeout = 5s
    maxRetries = 3
    retryDelay = 10s
    failureThreshold = 3
    resetTimeout = 30s
}