bot{
    url = ${BOT_PG_URL}
    username = ${BOT_PG_USERNAME}
    password = ${BOT_PG_PASSWORD}
    migrations-directory = "/Users/jpf/things/IntelliJ/link-tracker/migrations/bot"
}
scrapper{
    url = ${SCRAPPER_PG_URL}
    username = ${SCRAPPER_PG_USERNAME}
    password = ${SCRAPPER_PG_PASSWORD}
    migrations-directory = "/Users/jpf/things/IntelliJ/link-tracker/migrations/scrapper"
}