token = ${TG_BOT_TOKEN}
scrapper-url = ${SCRAPPER_URL}
database{
    url = ${PG_URL}
    username = ${PG_USERNAME}
    password = ${PG_PASSWORD}
}
kafka{
    servers = ${KAFKA_BOOTSTRAP_SERVERS}
    topic = ${KAFKA_LINK_UPDATE_TOPIC}
    consumer-group = ${KAFKA_LINK_UPDATE_CONSUMER_GROUP}
}
outbox{
    poll-interval-seconds = 10
    batch-size = 1
}